### ISSUE TITLE
Logarithmic depth integration with SilverLining is broken.

### ISSUE THREAD

**Issue by fkane** [gwaldron/osgearth#2296]
When substituting SilverLining's user shaders with the ones included in the osgEarth repository (https://github.com/gwaldron/osgearth/tree/master/src/osgEarthSilverLining/Shaders), no sky or clouds appear and some users report their application crashing due to shader compilation errors.

I dug into it the best I could, but I'm not sure how to fix this. There are a few problems I've identified:

- These shaders are based on an old version of our user shaders, and are missing all of the #ifdef wrappers around each function. I've attached the latest ones that should be used to start from (or just install our latest SilverLining SDK from https://dw9ne0o7jcasn.cloudfront.net/silverlining-sdk.exe)
- As far as I can tell, the osg_ProjectionMatrix uniform used inside your oe_LogDepth_vert function is no longer set anywhere (our shaders live outside of OSG / osgEarth). When I search for osg_ProjectionMatrix in osgEarth's source, it is only referenced within blocks of code that are now #ifdef'ed out.
- I don't think the oe_logDepth_frag() function in the fragment programs is actually getting called from anywhere (if it should be.)

osgViewer appears to use log depth by default now, so we're getting some confused customers who aren't getting the right results when loading the tests/silverlining.earth file even after replacing our user shaders. Having them pass --nologdepth and using our stock, unmodified shaders clears it up, but that's not a real solution.

Happy to help test things out on this.

[UserFunctions.zip](https://github.com/gwaldron/osgearth/files/11706799/UserFunctions.zip)

**Comment by gwaldron** [comment]
Hi Frank, we'll be happy to take a look at this.
It's not a surprise - we do not regularly keep the SL/Triton nodekits current with the latest versions, but should :)

**Comment by gwaldron** [comment]
Frank, I pushed an update the UserFunctions vertex shader files. They seem to work correctly.

The reason you don't see `osg_ProjectionMatrix` in the code is b/c we use a mechanism called `NativeProgramAdapter` that makes all uniforms visible to the SL shader, so we don't need to name them individually. I confirmed that this adapter is indeed exposing `osg_ProjectionMatrix` so hopefully all is well.

We also have a so-called "high precision log depth" shader (that uses a fragment shader) but it is rarely if ever used and we are considering just deprecating it ... so I did not bother updating the fragment shaders and in fact deleted them from the repository.

Will look at Triton next. Thanks.

**Comment by fkane** [comment]
Thank you! Were you actually able to run osgViewer (built against a recent SilverLining) with silverlining.earth and have the clouds appear with this change? I'm still seeing the same behavior here as before, but it might just be some local issue with my osg and/or osgEarth build.

**Comment by fkane** [comment]
Also, I see you removed the modified fragment shader... don't we need to also remove the out / varying oe_LogDepth_clipz from the vertex program then, if it's not used?

**Comment by fkane** [comment]
Sorry, typo - it is osgearth_viewer I am testing with. If you saw clouds there, it must just be due to my osgearth being out of date or something.

**Comment by gwaldron** [comment]
Hmm. Upon further review Frank, the clouds are there but the sorting still isn't quite right.
I will review this again and get back with you.

**Comment by gwaldron** [comment]
Pushed another push. Think I got it right this time for both SL and Triton. But it's Friday so who knows?
<img width="829" alt="image" src="https://github.com/gwaldron/osgearth/assets/326618/c2bd546a-77f2-4f90-9dbf-ae28af4a73aa">

**Comment by fkane** [comment]
Yes, can confirm SilverLining is working now! Thank you!

Triton however still has a few issues... it doesn't look like it's sorting properly, the new user-vert-functions.glsl won't compile because the "inverse" function isn't supported in the GLSL version it's using (that can be worked around by adding #extension GL_ARB_gpu_shader5: enable to the top of the file), and I don't think the user and license code is being successfully passed through from the triton.earth file - even with a valid license, it's popping up the invalid license message when starting. That one's confusing for end users because that dialog box is appearing behind osgEarth so it just looks like it locked up, when it's waiting for someone to hit OK on the box they can't see.

Want me to open up a new issue for the Triton stuff?

**Comment by gwaldron** [comment]
No, we can keep it here for now.

As for the Triton user/license, I found a bug and that should now be fixed.

I also added the shader5 extension to the glsl file(s). Would this not be necessary in SilverLining as well?

**Comment by fkane** [comment]
SilverLining uses a more recent GLSL version by default it seems, one that does support inverse().

I was fiddling with Triton in osgEarth a bit more myself this morning... for some reason it's not drawing the ocean all the way out once you pull back the camera a bit. Couldn't find any obvious reason :/ It almost looks like it thinks the Earth is much smaller than it is, but I suppose a depth sorting issue would make more sense.

I did notice the water appears black; if there's a way to boost the ambient light in the default scene there I think it would clear that up.

Thanks for poking at it!

**Comment by gwaldron** [comment]
Yeah I don't know either. I happens with or without the log depth. There is some distance from the camera at which is seems to 'snap'.

By default there is no light source at all, it's flat shaded and the water appears dark. If you run `osgearth_imgui --sky` you can use the Environment panel to adjust the time of day or the ambient floor.

**Comment by gwaldron** [comment]
If I run with depth testing off, I get this sort of thing. I can change the altitude at which is happens with the "mesh-switch-altitude" triton.config setting. It is as if the planar mesh is getting textured but the projected grid is not. (hope I have that terminology correct.)

**Comment by fkane** [comment]
Above mesh-switch-altitude, the ocean is rendered as a projected grid against the Earth's ellipsoid instead of a mesh surrounding the camera. It seems to work smoothly in my own test apps but I'll poke at some possible causes here.

**Comment by fkane** [comment]
So.... is osgEarth using a reverse depth buffer? I found things cleared up if I called this within TritonContext:

_ocean->SetClipDistances(-1.0, 1.0);

**Comment by gwaldron** [comment]
Triton.config says:
```
opengl-near-clip = 1.0
opengl-far-clip = -1.0
```
Did I do that?

**Comment by gwaldron** [comment]
Triton.config says:
```
opengl-near-clip = 1.0
opengl-far-clip = -1.0
```

**Comment by gwaldron** [comment]
Haha. Glad to hear it's working - thank you for all your help Frank!
