### ISSUE TITLE
Hide the polygon outlines

### ISSUE THREAD

**Issue by pks23** [gwaldron/osgearth#2700]
osgEarth Version (required): 3.7

Description of the problem: Not able to the polygon outlines 

What you have tried: Added custom shader for hiding the polygon by objectid.

I am working with osgEarth’s C++ API and have loaded a shapefile as a FeatureModelLayer. I need to hide the polygons upon selection, which I have achieved using shaders (making the polygon transparent) and objectid. However, the polygon outlines are still visible because they are rendered by LineDrawable. 

To hide the outlines, I attempted to find the corresponding geode using nodeIntersector to get the LineGroup containing the outlines. I then used the following code to identify the LineDrawable: 

osgEarth::LineGroup group = findAllNodesByType<osgEarth::LineGroup>(lyrNode).at(0); 

Despite enabling feature indexing for the FeatureSource, the LineDrawable objects are not tagged with objectid. 

Upon debugging, I found that in the BuildGeometryFilter class, the processLines function uses this line for tagging: 

if (context.featureIndex())  

{ 

    context.featureIndex()->tagDrawable(drawable, input); 

} 

However, the tagDrawable function only tags geometry class objects and does not tag the node, which prevents me from hiding the outlines effectively. 

Could you please help identify a solution to hide the polygon outlines?

**Comment by pks23** [comment]
I wrote a custom shader to hide a polygon using its ObjectID, and it works fine. But the polygon's outline is still visible. I tried to find the drawable for the outline, but it doesn’t have an ObjectID, so I couldn’t identify it.

**Comment by gwaldron** [comment]
Hey, now we are getting somewhere! Thanks for tracking down this bug. I have pushed a fix for this - please test and report back.

**Comment by pks23** [comment]
The drawables are still not tagged with objecID's. I can't find any attribute with objectID in attribute list.

![Image](https://github.com/user-attachments/assets/cfd60f9b-394b-4093-a7e1-19a8aae79d80)

I have attached the screenshot for the issue, as you can see I was able to hide the polygon but not the outline of the polygon.

**Comment by gwaldron** [comment]
I will need more information to help you at this point, please use the debugger to step into tagDrawable and/or getObjectIDs and show me what you find.
