### ISSUE TITLE
Cmake FindZLIB module import multi 'optimized' mark

### ISSUE THREAD

**Issue by robling** [gwaldron/osgearth#706]
When I tried to build osgEarth 2.7.0 with Cmake 3.5, vs2010, I got a link error which requires 'optimized.lib' and 'debug.lib'. I've find there is repeated 'optimized' mark in 'ZLIB_LIBRARY'. Adding aome 'MESSAGE' statements and I got:

```
MESSAGE(${ZLIB_LIBRARY}) : optimized /PATH/TO/zlib1.lib debug /PATH/TO/zlib1d.lib  
MESSAGE(${ZLIB_LIBRARIES}) : optimized /PATH/TO/zlib1.lib debug /PATH/TO/zlib1d.lib  
MESSAGE(${ZLIB_LIBRARY_RELEASE}) : /PATH/TO/zlib1.lib
MESSAGE(${ZLIB_LIBRARY_DEBUG}) :  /PATH/TO/zlib1d.lib
```

And the 'LINK_WITH_VARIABLES' Macro adds another 'optimized' mark to 'ZLIB_LIBRARY' which becomes the odd 'optimized.lib' linking target.

I change line 355 in osgearth/src/osgEarth/CMakeLists.txt ::
`LINK_WITH_VARIABLES(${LIB_NAME} OSG_LIBRARY OSGUTIL_LIBRA... ZLIB_LIBRARY ...`
remove ZLIB_LIBRARY in it and add the following line::
`LIST(APPEND ${LIB_NAME} ${ZLIB_LIBRARY})`

That works for me.

**Comment by gwaldron** [comment]
I wonder whether this is a CMake 3.x issue. I'm still using 2.8.x at the moment..

**Comment by emminizer** [comment]
For what it is worth, I'm using CMake 3.x (various versions above 3.1) and do not have this problem.  However, we explicitly set the ZLIB_LIBRARY and ZLIB_LIBRARY_DEBUG values on command line (and not ZLIB_LIBRARY_RELEASE nor ZLIB_LIBRARIES), so I'm not sure that my data point helps here.

Does your solution allow the ZLIB_LIBRARY_DEBUG to be linked in when in a debug configuration?  that's mildly helpful to avoid MSVCRT/MSVCRTD issues.

**Comment by remoe** [comment]
I'm using cmake 3.4.3 and VS2013. I don't have this issue.

**Comment by robling** [comment]
@gwaldron @emminizer 
I  used Cmake-gui tools to set variables. 
I just tried a minimal test cmake file and got different output between gui and cli tool:
https://imgur.com/delete/ur0o0YFuJmss9h6

**Comment by gwaldron** [comment]
Note, I resolved this issue (for me) by using a localized FindZLIB.cmake instead of the stock one... perhaps should commit to repo?

**Comment by bclay1297** [comment]
This problem still persists.  I am using osgEarth 2.9.0 development with cmake 3.6 with visual studio 2013 Optimized.lib and debug.lib are still part of the main osgEarth VS projects .  The solution given at the beginning of this thread does seem to fix the problem.  I am also having a problem getting to the osg/Config path.  I set the OSG_GEN_INCLUDE_DIR to the correct path but that does not seem to have any effect.  I have to append the path to the OSG_INCLUDE_DIR for the path to be included in the solution.

I am glad the solution works because I had to go through all of the projects to remove the libraries before finding this solution.  Thanks robling.

The attached file goes in osgearth/src/osgEarth as described above

[CMakeLists.txt](https://github.com/gwaldron/osgearth/files/597666/CMakeLists.txt)

**Comment by AlexBobkov** [comment]
I use cmake 3.9.1 and VS2015 and I have this issue.

**Comment by AlexBobkov** [comment]
FindZLIB.cmake from OpenSceneGraph repo should solve the problem.

**Comment by sshaw1885** [comment]
FindZLIB.cmake from the OpenSceneGraph repo doesn't solve the problem because it first looks for the FindZLIB distributed with CMake and uses that if it exists.  The problem arises when both the release and debug versions of the library are found in the same directory.  This causes CMake to add the "optimized" and "debug" keywords to the library list.  The solution that worked for me is to seperate the debug and release versions of ZLIB.

**Comment by damiandixon** [comment]
Just bumped into this one. I'm using cmake 3.9.0 and Visual Studio 2015. Dev of osgEarth as of yesterday.

I used the CMakeLists.txt provided by bclay1297.

**Comment by gwaldron** [comment]
obe - addressed in cmake modules update
