### ISSUE TITLE
master: osgEarth not building with master OSG

### ISSUE THREAD

**Issue by NikkittaP** [gwaldron/osgearth#919]
Pulled latest master OSG and osgEart on May 29.
Project **osgEarth** is not built with errors in **osgearth\src\osgEarth\DPLineSegmentIntersector.cpp** and **osgearth\src\osgEarth\Utils.cpp**:

```
Error	1	error C2039: 'LineSegmentIntersections' : is not a member of 'osg::KdTree'	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	264	osgEarth
Error	2	error C2065: 'LineSegmentIntersections' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	264	osgEarth
Error	3	error C2146: syntax error : missing ';' before identifier 'intersections'	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	264	osgEarth
Error	4	error C2065: 'intersections' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	264	osgEarth
Error	5	error C2065: 'intersections' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	265	osgEarth
Error	6	error C2228: left of '.reserve' must have class/struct/union	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	265	osgEarth
Error	7	error C2065: 'intersections' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	266	osgEarth
Error	8	error C3083: 'LineSegmentIntersections': the symbol to the left of a '::' must be a type	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	269	osgEarth
Error	9	error C2039: 'iterator' : is not a member of 'osg::KdTree'	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	269	osgEarth
Error	10	error C2065: 'iterator' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\DPLineSegmentIntersector.cpp	269	osgEarth
```

...and so on.

According to osgEarth forum user _Adrian Egli (3dhelp)_:

> Robert has changed the KDTree class and removed LineSegmentIntersections. He will may also change QuadTree which has similar LineSegmentIntersections struct implemented. Thus the osgEarth will no longer build against 3.5.6 version of OpenSceneGraph

**Comment by gwaldron** [comment]
DPLineSegmentIntersector pre-dates the changes in OSG to allow for double-precision calculations in the osgUtil::LineSegmentIntersector, so it may be possible to simply remove DPLSI in favor of LSI with the precision hint set.

**Comment by gwaldron** [comment]
I pushed a fix for this -- please test and report back.

**Comment by NikkittaP** [comment]
Thanks, tried to rebuild - some errors are gone, some are still here.
I'm not sure, maybe this is another issue, not connected with DPLineSegmentIntersector.
List of all errors while building **Core** folder:

```
Error	1	error C2065: '_previousWidth' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	72	osgEarth
Error	2	error C2065: '_previousHeight' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	73	osgEarth
Error	3	error C2065: '_firstTimeToInitEyePoint' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	88	osgEarth
Error	4	error C2065: '_firstTimeToInitEyePoint' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	89	osgEarth
Error	5	error C2065: '_previousEyePoint' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	91	osgEarth
Error	6	error C2065: '_previousLocalUp' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	99	osgEarth
Error	7	error C2065: '_previousWidth' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	103	osgEarth
Error	8	error C2065: '_previousHeight' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	103	osgEarth
Error	9	error C2065: '_previousProjection' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	104	osgEarth
Error	10	error C2065: '_previousPosition' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	105	osgEarth
Error	11	error C2065: '_firstTimeToInitEyePoint' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	111	osgEarth
Error	12	error C2065: '_previousEyePoint' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	132	osgEarth
Error	13	error C2065: '_previousLocalUp' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	133	osgEarth
Error	14	error C2065: '_previousWidth' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	134	osgEarth
Error	15	error C2065: '_previousHeight' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	135	osgEarth
Error	16	error C2065: '_previousProjection' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	136	osgEarth
Error	17	error C2065: '_previousPosition' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	137	osgEarth
Error	18	error C2065: '_matrixDirty' : undeclared identifier	C:\OSG\osgearth\src\osgEarth\Utils.cpp	139	osgEarth
Error	21	error LNK1104: cannot open file '..\..\lib\Debug\osgEarthd.lib'	C:\OSG\build_x86\osgearth\src\osgEarthSymbology\LINK	osgEarthSymbology
Error	22	error LNK1104: cannot open file '..\..\lib\Debug\osgEarthd.lib'	C:\OSG\build_x86\osgearth\src\osgEarthFeatures\LINK	osgEarthFeatures
Error	23	error LNK1104: cannot open file '..\..\lib\Debug\osgEarthd.lib'	C:\OSG\build_x86\osgearth\src\osgEarthAnnotation\LINK	osgEarthAnnotation
Error	24	error C2065: '_autoTransformCache' : undeclared identifier	C:\OSG\osgearth\src\osgEarthUtil\Controls.cpp	711	osgEarthUtil
Error	25	error C2228: left of '._matrix' must have class/struct/union	C:\OSG\osgearth\src\osgEarthUtil\Controls.cpp	711	osgEarthUtil
```

**Comment by NikkittaP** [comment]
Almost all errors are gone, 2 last strings from previous message still exist:
```
Error	9	error C2065: '_autoTransformCache' : undeclared identifier	C:\OSG\osgearth\src\osgEarthUtil\Controls.cpp	711	osgEarthUtil
Error	10	error C2228: left of '._matrix' must have class/struct/union	C:\OSG\osgearth\src\osgEarthUtil\Controls.cpp	711	osgEarthUtil
```

**Comment by gwaldron** [comment]
That one I'm not sure about -- seems to be an #if in there already -- perhaps you can take a look? I do not have OSG master built right now.

**Comment by NikkittaP** [comment]
It seems that it was my mistake, I've messed up source files. But I can't say for sure, I've broken OS on build PC :)
So I will make a clean install and rebuild everything from scratch with MS VS 2013 x64.
I hope I will report back on result tomorrow. Otherwise - next week.

**Comment by NikkittaP** [comment]
Ok, I've managed to reinstall and build everything from scratch.
Previous errors are gone. Now I have problem linking **ObjectLocator.obj**:

```
Error	12	error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osg::Matrixd::set(class osg::Quat const &)" (__imp_?set@Matrixd@osg@@QEAAXAEBVQuat@2@@Z) referenced in function "public: bool __cdecl osgEarth::Util::ObjectLocator::getOrientationMatrix(class osg::Matrixd &,unsigned int)const " (?getOrientationMatrix@ObjectLocator@Util@osgEarth@@QEBA_NAEAVMatrixd@osg@@I@Z)	C:\OSG\build_x64\osgearth\src\osgEarthUtil\ObjectLocator.obj
Error	13	error LNK1120: 1 unresolved externals	C:\OSG\build_x64\osgearth\lib\Debug\osgEarthUtild.dll
```

Sorry if I'm posting it in the wrong issue page.

**Comment by gwaldron** [comment]
pushed a fix.

**Comment by NikkittaP** [comment]
Perfect! It works, thanks a lot. I guess we can close this issue.
The only minor error I get is while building sample **osgearth_createtile**:

```
Error	1	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	91	Sample osgearth_createtile
Error	2	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	99	Sample osgearth_createtile
Error	3	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	100	Sample osgearth_createtile
Error	4	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	109	Sample osgearth_createtile
Error	5	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	110	Sample osgearth_createtile
Error	6	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	119	Sample osgearth_createtile
Error	7	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	120	Sample osgearth_createtile
Error	8	error C2660: 'CollectTriangles::operator ()' : function does not take 3 arguments	C:\Program Files\OpenSceneGraph\include\osg\TriangleFunctor	131	Sample osgearth_createtile

```

**Comment by gwaldron** [comment]
Fixed :)

**Comment by NikkittaP** [comment]
Done! Everything builds 👍
